name: .NET CI/CD (Railway)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore BugStore.sln
        working-directory: ./src

      - name: Build
        run: dotnet build BugStore.sln --no-restore -c Release
        working-directory: ./src

      - name: Test
        run: dotnet test BugStore.sln --no-build -c Release --verbosity normal
        working-directory: ./src

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # Linka o projeto específico
      - name: Link Railway project
        working-directory: ./src/BugStore.Api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway link --project ef350b04-c626-4039-a3ee-9d823b225792

      # Seleciona o ambiente específico
      - name: Select Railway environment
        working-directory: ./src/BugStore.Api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway environment ff30ac94-5f21-4e4e-b2d3-50b873727d8b

      # Opcional: fixar o serviço (ID da URL que você enviou)
      - name: Deploy to Railway (service pinned)
        working-directory: ./src/BugStore.Api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service aed77f3b-4f38-4d1f-9784-47748da7c530 --detach
