name: .NET CI/CD (Railway)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore BugStore.sln
        working-directory: ./src

      - name: Build
        run: dotnet build BugStore.sln --no-restore -c Release
        working-directory: ./src

      - name: Test
        run: dotnet test BugStore.sln --no-build -c Release --verbosity normal
        working-directory: ./src

      # Opcional: Validar Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/BugStore.Api/Dockerfile
          push: false
          tags: bugstore-api:test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- ALTERAÇÃO CHAVE: Usando a Ação Oficial do Railway CLI ---
      - name: Deploy to Railway
        uses: railwayapp/cli-action@v3
        with:
          # O token é passado com segurança.
          token: ${{ secrets.RAILWAY_TOKEN }}
          # Comando para fazer o deploy.
          command: up --service BugStoreApi --detach
          # Se o seu Dockerfile e código estiverem em um subdiretório (ex: ./src/BugStore.Api),
          # DESCOMENTE e ajuste a linha abaixo:
          root-path: ./src

      - name: Verificar Status do Deploy
        run: echo "Deploy iniciado. Verifique o status no painel do Railway."
