name: .NET CI/CD (Railway)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore BugStore.sln
        working-directory: ./src

      - name: Build
        run: dotnet build BugStore.sln --no-restore -c Release
        working-directory: ./src

      - name: Test
        run: dotnet test BugStore.sln --no-build -c Release --verbosity normal
        working-directory: ./src

      # Validação do Dockerfile
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate Dockerfile
        uses: docker/build-push-action@v5
        with:
          context: ./src
          file: ./src/BugStore.Api/Dockerfile
          push: false
          tags: bugstore-api:test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ACTION OFICIAL DO RAILWAY
      - name: Deploy to Railway
        uses: railwayapp/deploy-action@v1
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          command: up --service BugStoreApi --detach
          # Opcional: se o código está em subpasta
          working_directory: ./src

      - name: Verificar Status
        run: echo "Deploy iniciado. Verifique o status no painel do Railwa"
